# Generated by Django 4.0.4 on 2022-05-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('NOME', models.CharField(max_length=100)),
                ('ENDERECO', models.CharField(max_length=150)),
            ],
        ),
    ]
